-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Cliente (
EMAIL VARCHAR(15),
CPF INTEGER,
TELEFONE NUMERIC(10),
NOME VARCHAR(15),
PRIMARY KEY(EMAIL,CPF,TELEFONE,NOME)
)

CREATE TABLE VIAGENS (
PROMOCOES VARCHAR(15),
DESTINOS VARCHAR(15)
)

CREATE TABLE Agência de Viagen (
DESTINOS VARCHAR(15) PRIMARY KEY
)

CREATE TABLE CONTATO (
EMAIL VARCHAR(15),
TELEFONE VARCHAR(15)
)

ALTER TABLE VIAGENS ADD FOREIGN KEY(DESTINOS) REFERENCES Agência de Viagen (DESTINOS)
